---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    image: ami-000db10762d0c4c05
    instance_type: t2.micro
    vpc_subnet_id: subnet-38a38302
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  connection_options:
    ansible_user: ec2-user
  playbooks:
    converge: converge.yml
    cleanup: cleanup.yml
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
